events {}

http {
    server {
        listen 80;

        #server_frontend
        location / {
            proxy_pass http://localhost:80;
    }
        #server_backend
        location /api/ {
            proxy_pass http://localhost:5000/;
        }
    }
}